import { Product, Category } from './types'

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    description: 'Latest electronics and gadgets',
    image: '/categories/electronics.jpg',
  },
  {
    id: '2',
    name: 'Fashion',
    description: 'Trendy clothing and accessories',
    image: '/categories/fashion.jpg',
  },
  {
    id: '3',
    name: 'Home & Living',
    description: 'Furniture and home decor',
    image: '/categories/home-living.jpg',
  },
  {
    id: '4',
    name: 'Sports',
    description: 'Sports equipment and gear',
    image: '/categories/sports.jpg',
  },
  {
    id: '5',
    name: 'Books',
    description: 'Best sellers and classic reads',
    image: '/categories/books.jpg',
  },
]

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Wireless Headphones',
    price: 129.99,
    description: 'Premium sound quality with noise cancellation',
    image: '/products/wireless-headphones.jpg',
    category: 'Electronics',
    rating: 4.5,
    reviews: 128,
    inStock: true,
    specs: ['Battery: 20 hours', 'Noise Cancellation', 'Bluetooth 5.0'],
  },
  {
    id: '2',
    name: 'Classic Cotton T-Shirt',
    price: 39.99,
    description: 'Comfortable and durable everyday wear',
    image: '/products/cotton-tshirt.jpg',
    category: 'Fashion',
    rating: 4.2,
    reviews: 95,
    inStock: true,
    specs: ['Material: 100% Cotton', 'Available Colors: 5', 'Sizes: XS-XXL'],
  },
  {
    id: '3',
    name: 'Stainless Steel Watch',
    price: 199.99,
    description: 'Elegant timepiece with precision movement',
    image: '/products/stainless-watch.jpg',
    category: 'Fashion',
    rating: 4.7,
    reviews: 234,
    inStock: true,
    specs: ['Water Resistant: 50m', 'Sapphire Crystal', 'Swiss Movement'],
  },
  {
    id: '4',
    name: 'Modern Desk Lamp',
    price: 59.99,
    description: 'Adjustable LED lamp with touch control',
    image: '/products/desk-lamp.jpg',
    category: 'Home & Living',
    rating: 4.4,
    reviews: 67,
    inStock: true,
    specs: ['LED Technology', 'Adjustable Brightness', 'USB Charging Port'],
  },
  {
    id: '5',
    name: 'Professional Camera',
    price: 899.99,
    description: 'High-resolution DSLR for professionals',
    image: '/products/professional-camera.jpg',
    category: 'Electronics',
    rating: 4.8,
    reviews: 412,
    inStock: true,
    specs: ['24.2 MP Sensor', '4K Video', 'Full Frame'],
  },
  {
    id: '6',
    name: 'Running Shoes',
    price: 119.99,
    description: 'Comfortable cushioning for daily running',
    image: '/products/running-shoes.jpg',
    category: 'Sports',
    rating: 4.6,
    reviews: 189,
    inStock: true,
    specs: ['Cushioned Sole', 'Breathable Material', 'Sizes: 5-14'],
  },
  {
    id: '7',
    name: 'Designer Sunglasses',
    price: 149.99,
    description: 'Stylish UV protection eyewear',
    image: '/products/sunglasses.jpg',
    category: 'Fashion',
    rating: 4.3,
    reviews: 156,
    inStock: true,
    specs: ['UV400 Protection', 'Polarized Lenses', 'Designer Brand'],
  },
  {
    id: '8',
    name: 'Ergonomic Chair',
    price: 299.99,
    description: 'Premium office chair with lumbar support',
    image: '/products/ergonomic-chair.jpg',
    category: 'Home & Living',
    rating: 4.5,
    reviews: 203,
    inStock: true,
    specs: ['Lumbar Support', 'Adjustable Height', 'Breathable Mesh'],
  },
  {
    id: '9',
    name: 'Smart Watch',
    price: 249.99,
    description: 'Fitness tracking and notifications',
    image: '/products/smartwatch.jpg',
    category: 'Electronics',
    rating: 4.4,
    reviews: 342,
    inStock: true,
    specs: ['Heart Rate Monitor', 'Sleep Tracking', '7-day Battery'],
  },
  {
    id: '10',
    name: 'Yoga Mat',
    price: 29.99,
    description: 'Non-slip mat with carrying strap',
    image: '/products/yoga-mat.jpg',
    category: 'Sports',
    rating: 4.2,
    reviews: 78,
    inStock: true,
    specs: ['Thickness: 6mm', 'Non-slip Surface', 'Carrying Strap'],
  },
  {
    id: '11',
    name: 'Bestselling Novel',
    price: 19.99,
    description: 'Award-winning fiction novel',
    image: '/products/bestselling-novel.jpg',
    category: 'Books',
    rating: 4.6,
    reviews: 1234,
    inStock: true,
    specs: ['Pages: 384', 'Hardcover', 'Award Winner'],
  },
  {
    id: '12',
    name: 'Coffee Maker',
    price: 79.99,
    description: 'Programmable coffee maker with timer',
    image: '/products/coffee-maker.jpg',
    category: 'Home & Living',
    rating: 4.3,
    reviews: 112,
    inStock: true,
    specs: ['12-Cup Capacity', 'Programmable', 'Thermal Carafe'],
  },
]

export const PRICE_RANGES = [
  { label: 'Under $50', min: 0, max: 50 },
  { label: '$50 - $100', min: 50, max: 100 },
  { label: '$100 - $200', min: 100, max: 200 },
  { label: '$200 - $500', min: 200, max: 500 },
  { label: 'Over $500', min: 500, max: 10000 },
]

export const SORT_OPTIONS = [
  { label: 'Most Relevant', value: 'relevance' as const },
  { label: 'Price: Low to High', value: 'price-asc' as const },
  { label: 'Price: High to Low', value: 'price-desc' as const },
  { label: 'Newest', value: 'newest' as const },
]
